export const content = {
  hero: {
    headline: "A marketing strategist who specialises in search, AI visibility, and websites that convert.",
    subheadline: "I work with B2B businesses to improve their search and AI visibility, and to make sure their website earns it — with messaging that resonates, content that ranks, and a user experience that converts.",
    cta: "Apply for a no-obligation website review",
  },

  about: {
    heading: "The experience to know\nwhat good looks like.",
    body1: "I've been working in SEO and digital since 2010 — long enough to have seen every algorithm shift, and to know that the fundamentals haven't changed: the right content, on a well-structured site, aimed at the right audience. My background is in B2B, working with businesses that have grown significantly through digital, and my edge is being able to connect what search engines and AI crawlers reward with what actually resonates with buyers.",
    body2: "My approach is strategic rather than executional — I diagnose what's holding your digital performance back, build the plan to fix it, and work with you or your team to implement it. I'm also fluent in the AI and automation tools that help lean teams do more, and can help you build smarter systems around your digital activity without adding headcount.",
    linkText: "Full profile & experience →",
    sectors: [
      { emoji: "💻", label: "B2B Technology & SaaS" },
      { emoji: "💳", label: "Fintech & Financial Services" },
      { emoji: "🌐", label: "Digital-first B2B businesses" },
    ],
  },

  quoteStrip: {
    quote: "We took a brand and marketing function that was trying to find its feet to a sharp, pointed marketing instrument. A ridiculous amount of experience and insight.",
    name: "Tom Plater",
    role: "Head of Marketing, SharpCloud",
    avatarUrl: "/tom-plater.png",
  },

  painPoints: {
    headline: "Here's where\nI can help.",
    cards: [
      {
        emoji: "👻",
        titleLine1: "You're not showing up.",
        titleLine2: "On Google, in AI answers, or anywhere buyers are looking.",
        body: "Your competitors are appearing in search results and AI tools. You're not — and you're not sure why.",
      },
      {
        emoji: "🎯",
        titleLine1: "Traffic exists.",
        titleLine2: "But it's the wrong people.",
        body: "Leads are coming in but they're a bad fit. Your digital presence isn't attracting the buyers you actually want.",
      },
      {
        emoji: "💻",
        titleLine1: "Your website looks fine.",
        titleLine2: "It's just not doing anything.",
        body: "It ticks the boxes but it's not converting visitors, ranking in search, or making a strong case for your business.",
      },
    ],
  },

  results: {
    heading: "What I've delivered.",
    intro: "A track record built on real businesses, honest briefs, and outcomes I stand behind. Every engagement starts with a diagnosis — here's what happened next.",
    cards: [
      {
        name: "Business Language Services",
        title: "B2B Translation & Language Services",
        imageUrl: "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=900&q=80",
        logoUrl: "",
        stats: [
          { num: "81%", label: "Enquiry to client conversion rate" },
          { num: "Right-fit", label: "Enquiries only — B2C noise eliminated" },
          { num: "Growing", label: "New corporate pipeline month on month" },
        ],
        tags: "Positioning · Messaging · Web",
        situation: "Enquiries were coming in but most were from individual customers rather than the corporate clients they actually wanted. Marketing was unfocused and the website wasn't speaking to the right audience.",
        whatWeDid: "Repositioned the brand and messaging around their B2B specialism, rebuilt the website copy, and restructured how enquiries were framed and routed.",
        result: "Conversion jumped to 81% because the leads arriving were already the right fit — and the B2C noise stopped almost immediately.",
        quote: "",
        quoteAuthor: "",
      },
      {
        name: "CSM",
        title: "UK B2B Manufacturer",
        imageUrl: "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?w=900&q=80",
        logoUrl: "",
        stats: [
          { num: "4–8×", label: "Increase in monthly lead volume" },
          { num: "40–50", label: "Leads per month, up from 5–10" },
          { num: "Organic", label: "SEO and channel strategy driven" },
        ],
        tags: "SEO · Channel strategy",
        situation: "Good product, solid sales from word-of-mouth — but almost no digital presence. Marketing was mostly trade shows and referrals, with no structured way to generate leads online.",
        whatWeDid: "Built an organic SEO strategy from scratch and put in place a proper digital channel approach tailored to how their buyers actually searched and made decisions.",
        result: "Monthly leads grew from 5–10 to 40–50 — a 4–8× increase entirely through organic channels, with no paid media spend.",
        quote: "",
        quoteAuthor: "",
      },
      {
        name: "SharpCloud",
        title: "Roadmapping & Strategy Software",
        imageUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=80",
        logoUrl: "",
        stats: [
          { num: "2×", label: "High-quality leads — more than doubled" },
          { num: "#1", label: "Google ranking for primary product keyword" },
          { num: "+20%", label: "Total lead volume increase" },
        ],
        tags: "SEO · Paid media · Positioning",
        situation: "An established SaaS product with real customers but limited marketing traction. They needed more of the right leads, not just more activity — and a sharper sense of how to position the product.",
        whatWeDid: "Overhauled the positioning, built an SEO foundation targeting the right keywords, and introduced a paid media programme focused on high-intent buyers.",
        result: "High-quality leads more than doubled, the primary product keyword hit #1 on Google, and total lead volume grew by 20%.",
        quote: "We took a brand and marketing function that was trying to find its feet to a sharp, pointed marketing instrument. A ridiculous amount of experience and insight.",
        quoteAuthor: "Tom Plater, Head of Marketing — SharpCloud",
      },
      {
        name: "Stitch Money",
        title: "Fintech & Payments",
        imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=900&q=80",
        logoUrl: "",
        stats: [
          { num: "XX%", label: "Placeholder — add real stat" },
          { num: "XX", label: "Placeholder — add real stat" },
          { num: "XX", label: "Placeholder — add real stat" },
        ],
        tags: "Strategy · Positioning",
        situation: "",
        whatWeDid: "",
        result: "",
        quote: "",
        quoteAuthor: "",
      },
    ],
  },

  services: {
    heading: "What I offer.",
    cards: [
      {
        badge: "Fixed fee",
        featured: false,
        name: "Website\nPerformance Audit",
        price: "£1,600",
        priceNote: "fixed fee",
        description: "A structured review of your website — how it's performing, where it's losing people, and whether it's working as hard as it should. I use analytics and behaviour data alongside best practice to build a clear picture, and come back with findings and recommendations you can act on straight away.",
        includesLabel: "Includes",
        features: [
          "Briefing call & pre-work review",
          "Website structure & UX assessment",
          "Messaging & conversion analysis",
          "Written findings & recommendations",
        ],
        cta: "",
        ctaLink: "",
      },
      {
        badge: "Fixed fee",
        featured: false,
        name: "SEO & AI\nVisibility Audit",
        price: "£1,600",
        priceNote: "fixed fee",
        description: "A review of how visible your business is in search engines and AI tools — where you rank, where you don't, and what's holding you back. I'll assess your technical foundations, content structure, and how you're performing versus competitors and showing up in AI, and give you a clear picture of where to focus.",
        includesLabel: "Includes",
        features: [
          "Technical foundations review",
          "Content structure & gap analysis",
          "Competitor performance benchmarking",
          "AI visibility & citation assessment",
          "Written findings & recommendations",
        ],
        cta: "",
        ctaLink: "",
      },
      {
        badge: "Ongoing",
        featured: true,
        name: "Looking for\nOngoing Support",
        price: "",
        priceNote: "",
        description: "Some clients need more than a one-off audit. If you're looking for someone to work alongside you on an ongoing basis — improving your search visibility, keeping your website performing, and making sure your digital activity is joined up — get in touch and we'll figure out what makes sense.",
        includesLabel: "",
        features: [],
        cta: "Get in touch",
        ctaLink: "/contact",
      },
    ],
  },

  cta: {
    heading: "Apply for a no-obligation\nwebsite review.",
    subheading: "I'll spend an hour reviewing your website and we'll get on a call to talk through what I find — no slides, no fluff, just an honest assessment of what's working, what isn't, and where I'd focus first.",
    buttonText: "Apply for a website review",
    email: "hello@discern.marketing",
  },

  footer: {
    tagline: "Website Performance | SEO & AI Visibility | PPC",
    email: "hello@discern.marketing",
    whatsapp: "https://wa.me/447700000000",
    linkedin: "https://www.linkedin.com/in/arekestall",
  },
};
